config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'

  get 'homes/about_us'

  get 'homes/contact_us'
  get 'homes/careers'
  

  get 'homes/home'

  resources :products do
    collection do
      get 'product_details'
    end
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def about_us
  end

  def contact_us
  end

  def home
  end

  def careers
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def product_details
		@item = params[:item]
	end

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/homes/about_us.html.erb
</div>
<div class="about_bg">
    <div class="main">
        <div class="about_title">Company Profile

        </div>

        <div class="about_text">
            <h4>GMP, ISO and USFDA Certified</h4>
            <p></p>
            <p>Being farmers ourselves we are closely associated with farmers and suppliers across the world, we are involved right from initial stages of farming to supply of finished products on time, at an affordable prices and hassle free to our Customers.</p>
            <p>RELISH AGRO FOOD can provide current market updates and recommend customers when is the best time to buy and make it easier for our valuable customers to make critical buying decisions, that is one of the benefits working with RELISH AGRO FOOD. We even provide door delivery to your warehouse and deal with FDA and Customs for you so our customers can concentrate on other important things.</p>
            <img src="about_us/fro_logo.png" alt="">
            <p>Our relationships developed over long periods with our growers have allowed us to supply quality products to the industry and maintain continuity of supply even through poor harvests.</p>
            <p>RELISH AGRO FOOD is particularly well known for supply of food ingredients from harvest to supply of finished goods on time. We can offer any port delivery or we can even offer door delivery to your warehouse to make it easier for our customers.</p>
            <p>Serving our customers directly from our office in India, our efforts are focused on providing a complete line of superior quality FROZEN VEGETABLES &amp; FRUITS at competitive prices and value added service. We strive to build lasting supply relationships, offer value-added services and help our customers meet their cost savings goals.</p>
            <p>Honest dealings with customers, coupled with outstanding people and products, add up to the high level of customer service expected of RELISH AGRO FOOD, In short, we will be our customer's most valued supplier.</p>
            <p>It starts with a fair and open sharing of expectations between each and everyone. It guides us throughout the business day, with our suppliers, our customers, and within the communities, we call home. The result is a hard-earned reputation for honesty and credibility in all that we do.</p>
            <p>Always offers competitive prices and supplies goods to customer requirements. Our key to this is the direct relationship we develop with each customer. You will only ever need one contact at RELISH AGRO FOOD to deal with your every enquiry. All our personnel are multi-skilled and we look forward doing business with you on a long-term basis.</p>

        </div>

    </div>
    <div class="float_clear"></div>
    <div class="member_bg">
        <div class="main">
            <div class="member_title">MEMBER OF</div>
            <div class="member_text">
                <%= image_tag "member_img.png" %>
                <p>APEDA – Agricultural &amp; Processed Food Products Development Authority </p>
                <p>FCER – Food Canning Establishment Registration, Food &amp; drug Adminitration</p>
                <p>FPO – Fruit Product Order</p>
                <p>Spices Board and FSSAI – License No. 10014021001078</p>
                <p>IEC – Import Export Code, DGFT Spice Board of India</p>
            </div>

            <div class="float_clear"></div>
        </div>
    </div>
    <div class="main">
        <div class="about_title">Quality Policy</div>
        <div class="quality_text">
            <%= image_tag "policy_img.png" %>
            <p>RELISH AGRO FOOD quality means that you will receive the best materials available. Each product is strictly controlled throughout its life from planting and harvesting to delivery to your door.</p>
            <p>RELISH AGRO FOOD is based on direct relationships between our team in India and our growers. Every process is carefully checked and tested on a regular basis to achieve consistency in providing </p>
            <p>Excellent quality. Wherever necessary, full audits of each process line are carried out by professional representatives.</p>
            <p>Specific testing regimes, such as Lot Sample testing by third party international testing agency to assure the status of our products is part of our standard operating procedures.</p>
            <p>Our companies employ a combination of quality systems to ensure the very best product is achieved year on year. Our growers are supported by qualified representatives appropriate to their particular crops to ensure that RELISH AGRO FOOD gives back not just cash for crops but also to achieve better management of the supply chain.</p>
        </div>
        <div class="float_clear"></div>
        <div class="about_title">Service</div>
        <div class="about_text">
            <%= image_tag "food_img.png" %>
            <p>Whether serving our customers directly from our Bellevue office or through our office in India, our efforts are focused on providing a complete line of superior quality ingredients at competitive prices and Relish value added service. We strive to build lasting supply relationships, offer value-added services and help our customers meet their cost savings goals. </p>
            <p> Honest dealings with customers, coupled with outstanding people and products, add up to the high level of customer service expected of Relish Agro Food In short, we will be our customer's most valued supplier.</p>

            <div class="about_title">Values</div>
            <p>Excellence, honesty, quality, and Relish value added service. These are the Relish Agro Food principles that have shaped and continue to guide this solid, growing and vertically integrated company.</p>

            <div class="about_title">Excellence</div>
            <p>It's accomplished by hands-on management and strict attention to detail at every level, by people who make excellence a personal goal, as well as a corporate one. Given the best resources and encouragement in aggressive investment and thoughtful risk-taking, we maintain our leadership position.</p>

            <div class="about_title">Honesty</div>
            <p>It starts with a fair and open sharing of expectations between each and everyone. It guides us throughout the business day, with our suppliers, our customers, and within the communities we call home. The result is a hard-earned reputation for honesty and credibility in all that we do.</p>

            <div class="about_title">Pricing Policy</div>
            <p>Relish Agro Food always offers competitive prices and supplies goods to customer requirements. Our key to this is the direct relationship we develop with each and every customer. You will only ever need one contact at Relish Agro Food to deal with your every enquiry. All our personnel are multi-skilled and we look forward doing business with you on a long term basis.</p>

        </div>

    </div>

    <div class="float_clear"></div>
</div>
<style type="text/css">
    #header {
        background-color: black;
        /*background: rgba(0, 0, 0, 0.5);*/
    }
    
    #page_wrapper {
        background-repeat: repeat;
        background-position: left top;
        background-attachment: scroll;
        position: relative;
        overflow: hidden;
        z-index: 99999;
        min-height: 35vh;
    }
</style>

app/views/homes/careers.html.erb
</div>
<div class="main">
    <div class="about_title">Careers</div>

    <div class="contact_left wow fadeInDown animated" data-wow-offset="0" data-wow-delay="0.2s" style="visibility: visible;-webkit-animation-delay: 0.2s; -moz-animation-delay: 0.2s; animation-delay: 0.2s;">

        Please fill out the form and we’ll get back to you soon if your resume fits with our hunt.
        <form action="careers.php" method="post" enctype="multipart/form-data" name="frm2" id="frm2" onsubmit="return validate(this); ">
            <script language="JavaScript" type="text/javascript">
                function validateEmail(fld) {
                    var my = fld;
                    var attherate = my.indexOf("@");
                    var lastattherate = my.lastIndexOf("@")
                    var dotpos = my.lastIndexOf(".");
                    var posspace = my.indexOf(" ");
                    var totallen = my.length;
                    if (attherate <= 0 || dotpos <= 0 || attherate > dotpos || (dotpos - attherate) <= 1 || (dotpos == totallen - 1) || posspace > -1 || attherate != lastattherate) {
                        return false;
                    } else {
                        return true;
                    }
                }

                function validate(frm) {
                    if (frm.Name.value == "") {
                        alert("Please Enter Name");
                        frm.Name.focus();
                        return false;
                    } else if (frm.Phone.value == "" || isNaN(frm.Phone.value) == true) {
                        alert("Please Enter Valid Phone");
                        frm.Phone.focus();
                        return false;
                    } else if (frm.Email.value == "" || !(validateEmail(frm.Email.value))) {
                        alert("Please Enter Email");
                        frm.Email.focus();
                        return false;
                    } else if (frm.Resume.value == "") {
                        alert("Please Attach Resume");
                        frm.Resume.focus();
                        return false;
                    } else {
                        return true;
                    }
                }
            </script>
            <br>
            <br>

            <div class="compulsory">(*Represents compulsory fields)</div>
            <div class="form_field"><span>Name * :</span>
                <input type="text" name="Name" id="Name">
            </div>
            <div class="form_field"><span>Phone * :</span>
                <input type="text" name="Phone" id="Phone">
            </div>
            <div class="form_field"><span>Email * :</span>
                <input type="text" name="Email" id="Email">
            </div>
            <div class="form_field"><span>Resume * :</span>
                <input name="Resume" type="file" id="Resume">
            </div>
            <div class="form_field"><span class="lastnone">&nbsp;</span>
                <input type="submit" name="submit" value="Submit" class="button">
                <input name="Reset" type="reset" class="button" id="Reset" value="Reset">
            </div>
            <div class="float_clear"></div>
        </form>

    </div>

</div>
<style type="text/css">
    #header {
        background-color: black;
        /*background: rgba(0, 0, 0, 0.5);*/
    }
    
    #page_wrapper {
        background-repeat: repeat;
        background-position: left top;
        background-attachment: scroll;
        position: relative;
        overflow: hidden;
        z-index: 999999;
        min-height: 35vh;
    }
</style>

app/views/homes/contact_us.html.erb
<%= form_tag(homes_contact_us_path, method: :get) do %>
	<label>Name</label>
	<%= text_field_tag :name, '',placeholder: 'Enter Name' %>
	<label>Email</label>
	<%= text_field_tag :email, '', placeholder: 'Please Enter Email' %>
	<label>Subject</label>
	<%= text_field_tag :subject, '', placeholder: 'Please Enter Subject' %>
	<label>Description</label>
	<%= text_field_tag :message, '', placeholder: 'Please Enter Description' %>
	<%= submit_tag "Send Message" %>
<% end %>

app/views/homes/home.html.erb
<h1>Homes#home</h1>
<p>Find me in app/views/homes/home.html.erb</p>

app/views/homes/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content=" width=device-width, initial-scale=1">
    <title>Ossom Foods</title>
    <!-- Fonts -->
    <link href="//fonts.googleapis.com/css?family=Amatic+SC:400,700%7CMontserrat:400,700%7COpen+Sans:300,400,700%7CRoboto" rel="stylesheet">
</head>

<body>
  <div class="container">
    <div class="row mt-20">
      <div class="col-md-12">
      </div>
    </div>
  </div>
<div class="top-silder">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
         <%= image_tag 'ny.jpg'%>
      </div>

      <div class="item">
        <%= image_tag '2.jpg'%>
      </div>

      <div class="item">
         <%= image_tag '3.jpg'%>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
    <section id="main-product br-bottom" class="product-section bg-color--white">
        <div class="container-fluid container--delivery">
            <div class="row">
                <div class="col-sm-12">
                    <div class="spacer-70">
                    </div>
                </div>
                <div class="col-12 col-sm-6" style="z-index:6;">
                    <div class="col-wrapper txt-center">
                        <div class="img-wrapper-margin">
                        <%=link_to (image_tag "main-product1", class: ' main-product-img img-fluid image-box-img'), products_path %>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-6" style="z-index:6;">
                    <div class="col-wrapper txt-center">
                        <div class="img-wrapper-margin">
                         <%=link_to (image_tag "main-product2", class: 'img-fluid main-product-img image-box-img'), products_path %>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="spacer-70">
                    </div>
                </div>
            </div>
        </div>
     </section>
	 <section class="mt-30 mb-20">
	 	<span class="product-label product1-label"><b>FROZEN VEGETABLES</span>
	 	<span class="product-label product2-label"><b>REDAY TO EAT</span></b>
	 </section>
    <!--start first paralax-->
    <section class="specialities">
        <div class="welcome_bg">
                <div class="main">
                    <div class="welcome_title wow fadeInDown animated" data-wow-offset="0" data-wow-delay="0.8s" style="visibility: visible;-webkit-animation-delay: 0.8s; -moz-animation-delay: 0.8s; animation-delay: 0.8s;">Welcome to Ossom Foods </div>
                    <div class="welcome_text wow fadeInDown animated" data-wow-offset="0" data-wow-delay="0.9s" style="visibility: visible;-webkit-animation-delay: 0.9s; -moz-animation-delay: 0.9s; animation-delay: 0.9s;">Being a farmers ourselves we are closely associated with farmers and suppliers across the world, 
                        We are involved right from initial stages of farming to supply of finished products on time, 
                        at a affordable prices and hassle free to our Customers. </div>
                    <div class="welcome_more_btn btn btn-warning btn-sm button cta hvr-float-shadow"> <a href="about_us.html">More</a> </div>
                </div>
            </div>
    </section>
    <div id="location">
        <iframe src="https://snazzymaps.com/embed/54951"></iframe>
    </div>
    <!-- Start footer -->
    <footer id="subscribe" class="pgb-60 pgt-180  bg-color--dark">
        <div class="container custom_width">
            <div class="row">
                <div class="col-md-12">
                    <div class="newsletter-wrapper">
                        <div class="title-block txt-center">
                            <h1 class="title-block__title title-block__title--delivery txt-light">Contact Us</h1>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-4 col-lg-7">
                        <form class="newsletter-form">
                            <input type="text" name="nwl_email" class="nwl-input" value placeholder="Your email address" required="required">
                            <br>
                            <input type="text" name="nwl_email" class="nwl-input" value placeholder="subject" required="required" style="height: 150px; margin-top: 10px">
                            <br>

                        </form>
                        <div class="newsletter-form__result"></div>
                    </div>
                </div>
                <div class="col-sm-12 ">
                    <div class="contact-us-btn">
                        <button type="submit" name="submit" class="align-items-center nwl-buton btn--round btn--color"> SUBSCRIBE</button>
                    </div>
                </div>
                <div class="col-12">
                    <div class="footer-wrapper">
                        <ul class="footer-social">
                            <li class="footer-social__item "><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li class="footer-social__item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li class="footer-social__item"><a href="#"><i class="fab fa-dribbble"></i></a></li>
                            <li class="footer-social__item"><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                        </ul>
                        <ul class="footer-nav">
                            <li class="footer-nav__item"><a class="footer-navlink" href="index.html#about">ABOUT US</a></li>
                            <li class="footer-nav__item"><a class="footer-navlink" href="index.html#menu">PRODUCT</a></li>
                            <li class="footer-nav__item"><a class="footer-navlink" href="index.html#offer">CAREER</a></li>
                            <li class="footer-nav__item"><a class="footer-navlink" href="index.html#reservation">SALES INQUIRY</a></li>
                            <li class="footer-nav__item"><a class="footer-navlink" href="index.html#location">CONTACT US</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!--  </div> -->
    <!-- /.#page_wrapper -->
    <a href="#" class="totop totop-vissible">
        <svg class="svg-inline--fa fa-chevron-up fa-w-14" aria-hidden="true" data-prefix="fas" data-icon="chevron-up" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg="">
            <path fill="currentColor" d="M240.971 130.524l194.343 194.343c9.373 9.373 9.373 24.569 0 33.941l-22.667 22.667c-9.357 9.357-24.522 9.375-33.901.04L224 227.495 69.255 381.516c-9.379 9.335-24.544 9.317-33.901-.04l-22.667-22.667c-9.373-9.373-9.373-24.569 0-33.941L207.03 130.525c9.372-9.373 24.568-9.373 33.941-.001z"></path>
        </svg>
        <!-- <i class="fas fa-chevron-up"></i> -->
        <p class="totop-text">TOP</p>
    </a>

    <!-- load scripts -->
    <!-- <script src="js/plugins/jquery-3.3.1.min.js"></script> -->
    <!-- <script src="js/plugins/bootstrap.min.js"></script> -->
    <!-- <script src="addons/jquery.smooth-scroll.min.js"></script> -->
    <!--popup script-->
    <!-- <script src="addons/Magnific-Popup/jquery.magnific-popup.js"></script> -->
    <!--parallax script-->
    <!-- <script  src="addons/Paraxify/paraxify.min.js"></script> -->
    <!-- <script  src="addons/modernizr-custom.js"></script> -->

    <script>
        FontAwesomeConfig = {
            searchPseudoElements: true
        };
        $(window).load(function() {
        $('.flexslider').flexslider({
            animation: "slide"
          });
        });
    </script>
    <!-- <script defer src="fonts/font-awesome/js/fontawesome-all.js"></script> -->
    <!-- Main template script -->
    <!-- <script src="js/script.js"></script> -->
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodApp</title>
   <link href="//fonts.googleapis.com/css?family=Amatic+SC:400,700%7CMontserrat:400,700%7COpen+Sans:300,400,700%7CRoboto" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="page_wrapper">
	<%= render template: "layouts/header"%>
	<%= yield %>
</div>

</body>
</html>

app/views/layouts/header.html.erb
<ul class="ph__resMenu">
  <li class="ph__resMenu-back">
    <span class="ph__resMenu-backIcon"><i class="fas fa-angle-left"></i></span>
		<a href="#" class="ph__resMenu-backLink">Back</a>
  </li>
  <li><%= link_to "Home", root_path, classs: 'ph__menu-link' %></li>
  <li><%= link_to "About us", homes_about_us_path, classs: 'ph__menu-link' %></li>
  <!-- <li><a class="active" href="index.html#about"><span>About us</span></a></li> -->
  <li><%= link_to "Product", products_path, class: 'ph__menu-link' %></li>
  <li><%= link_to "Careers", homes_careers_path, class: 'ph__menu-link' %></li>
  <li><a class="ph__menu-link" href="index.html#location"><span>sales inquiry</span></a></li>
  <li><a href="index.html#subscribe"><span>Contact Us</span></a></li>
</ul>
<header id="header" class="site-header header--sticky site-header--absolute header--is-sticked">
    <div class="site-header-main-wrapper">
      <div class="container siteheader-container">
					<div class="flex-col flex-basis-auto">
            <div class="flex-row site-header-row site-header-main">
              <!-- left column - logo -->
              <div class="flex-col flex flex-start-x flex-center-y flex-basis-auto flex-grow-0 flex-sm-half site-header-col-left">
                <div class="logo-container">
                    <div class="site-logo">
                        <a href="index.html" class="site-logo-anch">
                            <span class="logo-img-sticky site-logo-img-sticky">
                              <svg xmlns="http://www.w3.org/2000/svg" width="34" height="30" viewBox="0 0 34 30">
                                <path id="Forma_1" data-name="Forma 1" class="cls-1" d="M41.962,13c-1.522-2.569-4.5-4.042-8.159-4.042A11.446,11.446,0,0,0,26.915,11.6a11.626,11.626,0,0,0-8.564-3.589,9.588,9.588,0,0,0-7.99,4.671A7.51,7.51,0,0,0,9.2,18.745c0.949,3.962,4.923,6.906,6.593,7.992v9.805a1.439,1.439,0,0,0,1.428,1.449H36.1a1.438,1.438,0,0,0,1.428-1.449V25.992a8.978,8.978,0,0,0,4.037-3.735C43.349,18.862,43.489,15.573,41.962,13Zm-2.914,7.9c-2.366,4.513-12.461,4.7-16.152,4.385a1.449,1.449,0,0,0-.237,2.887c0.158,0.014,1.235.1,2.812,0.1a33.885,33.885,0,0,0,9.206-1.16V35.1H18.652V25.923a1.453,1.453,0,0,0-.735-1.266c-0.05-.028-5.057-2.9-5.94-6.6a4.633,4.633,0,0,1,.759-3.771A6.808,6.808,0,0,1,18.425,10.9a8.88,8.88,0,0,1,6.354,2.607,24.4,24.4,0,0,0-3.222,4.1,1.46,1.46,0,0,0,.48,1.988A1.417,1.417,0,0,0,24,19.113c0.044-.073,4.428-7.261,9.806-7.261,2.637,0,4.718.962,5.712,2.637S40.338,18.434,39.048,20.9Z" transform="translate(-9 -8)"/>
                              </svg>
                            </span>
                            <%= image_tag "logo.png", style: 'border-radius: 10px;', size: '196X46', class: 'logo-img site-logo-img' %>
                            <!-- <img class="logo-img site-logo-img" src="image/img-assets/logo.png" alt="logo" title="phaeton" width="196" height="36"> -->
                            <%#= image_tag "logo.jpg", size: '196X36', class: 'logo-img site-logo-img' %>
                        </a>
                    </div>
                </div>
              </div>
							<!-- center column - navigation menu -->
							<div class="fxb-col fxb fxb-center-x fxb-center-y fxb-basis-auto site-header-col-center site-header-main-center">
								<ul class="ph__mainMenu clearfix">
                  <li><%= link_to "Home", root_path, classs: 'ph__menu-link' %>
                    <!-- <a class="ph__menu-link" href="index.html#about"><span>Home</span></a> --></li>
									<li><%= link_to "About us", homes_about_us_path, classs: 'ph__menu-link' %></li>
									<li><%= link_to "Product", products_path, classs: 'ph__menu-link' %></li>
                  <li>
                    <div class="dropdown">
                      <%= link_to "Product", products_path, class: 'ph__menu-link dropbtn' %>
                      <!-- <button class="dropbtn">Dropdown</button> -->
                      <div class="dropdown-content">
                      <%= link_to 'Frozen Vagitables', products_path, class: 'product-link' %>
                      <%= link_to 'Ready To Eat', products_path, class: 'product-link' %>
                      </div>
                    </div>
                  </li>
                  <li class="img-loaded site-logo-anch"><a class="ph__menu-link logo-link" href="index.html#home">
										<span class="logo-img-sticky site-logo-img-sticky">
										<!-- 	<svg xmlns="http://www.w3.org/2000/svg" width="34" height="30" viewBox="0 0 34 30">
												<path id="Forma_2" data-name="Forma 2" class="cls-1" d="M41.962,13c-1.522-2.569-4.5-4.042-8.159-4.042A11.446,11.446,0,0,0,26.915,11.6a11.626,11.626,0,0,0-8.564-3.589,9.588,9.588,0,0,0-7.99,4.671A7.51,7.51,0,0,0,9.2,18.745c0.949,3.962,4.923,6.906,6.593,7.992v9.805a1.439,1.439,0,0,0,1.428,1.449H36.1a1.438,1.438,0,0,0,1.428-1.449V25.992a8.978,8.978,0,0,0,4.037-3.735C43.349,18.862,43.489,15.573,41.962,13Zm-2.914,7.9c-2.366,4.513-12.461,4.7-16.152,4.385a1.449,1.449,0,0,0-.237,2.887c0.158,0.014,1.235.1,2.812,0.1a33.885,33.885,0,0,0,9.206-1.16V35.1H18.652V25.923a1.453,1.453,0,0,0-.735-1.266c-0.05-.028-5.057-2.9-5.94-6.6a4.633,4.633,0,0,1,.759-3.771A6.808,6.808,0,0,1,18.425,10.9a8.88,8.88,0,0,1,6.354,2.607,24.4,24.4,0,0,0-3.222,4.1,1.46,1.46,0,0,0,.48,1.988A1.417,1.417,0,0,0,24,19.113c0.044-.073,4.428-7.261,9.806-7.261,2.637,0,4.718.962,5.712,2.637S40.338,18.434,39.048,20.9Z" transform="translate(-9 -8)"/>
											</svg> -->
										</span>
										<%= image_tag "logo.png", style: 'border-radius: 10px;', size: '196X46', class: 'logo-img site-logo-img' %>
									</a></li>
									 <li><%= link_to "Careers", homes_careers_path, class: 'ph__menu-link' %></li>
									<li><a  class="ph__menu-link" href="index.html#location"><span>sales inquiry</span></a></li>
									<li><a class="ph__menu-link" href="index.html#subscribe"><span>Contact Us</span></a></li>
							 </ul><!--/.ph__mainMenu-->
							</div>
							<!-- right column - navigation menu -->
              <div class="flex-col flex flex-end-x flex-center-y flex-basis-auto flex-sm-half site-header-col-right site-header-main-right">
                  <div class="main-menu-wrapper">
                    <div class="sh-component menu-wrapper">
                       <div class="ph__menuWrapper">
                         <div class="ph__mainMenu-trigger">
                           <a href="#" class="ph__menuBurger">
                             <span></span>
                             <span></span>
                             <span></span>
                           </a>
                         </div><!--/.ph__mainMenu-trigger-->
                        </div><!--/.ph__menuWrapper-->
                    </div>
                  </div>
              </div>
            </div>
          </div>
      </div>
    </div>
</header>

app/views/products/_product_2.html.erb
<section id="about" class="bg-color--white">
  <div class="row no-gutters">
		<div class="col-12 col-sm-8 align-self-center">
				<div class="about-col__wrapper">
					<div class="cont-width-94">
						<div class="title-block">
							<h2 class="title-block__title--about">Extrusion Grade Potato Flakes
							</h2>
							<p class="title-block__subtitle--about ">The choice of savoury makers. We customise products in this category to fit the kind of extrusion the customer is performing. Let us know your product and we promise you a best suit.</p>
						</div>
						<a href="#" class="btn btn--line btn--30 btn--section">Read more </a>
					</div>
			</div>
		</div>
		<div class="col-12 col-sm-4 align-self-center">
			<div class="col-wrapper-img">
				<%= image_tag "Potato-Flakes5", class: 'img-fluid image-cover-fit image-box-img' %>
				<!-- <img src="https://demos.hogash.com/phaeton-restaurant-html/images/about-chefs.jpg" class="img-fluid image-cover-fit image-box-img" alt="" title="about-chefs"> -->
			</div>
		</div>
	</div>
</section>